language: python
python:
  - "3.6"
env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=

matrix:
   include:
        - python: 3.6
          env: PYTHONASYNCIODEBUG=
          addons:
              mariadb: 10.1
			  
before_script:
    - "mysql -e 'SELECT VERSION()'"
    - "mysql -e 'DROP DATABASE IF EXISTS firstaioexample; create database firstaioexample  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest