language: python
python:
  - "3.6"
env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=

matrix:
   include:
        - python: 3.6
          env: PYTHONASYNCIODEBUG=
          addons:
              mariadb: 10.1
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest